import { redirect } from "next/dist/server/api-utils";
import { themColor } from "./theme/themColor";

export const widgets = [
  {
    id: "1",
    name: "WhatsApp",
    color: "#000",
    icon: "/icons/whatsapp.svg",
    background: "#54CF61",
  },
  {
    id: "2",
    name: "Messenger",
    icon: "/icons/messenger.svg",
    color: "#fff",
    background: "#0190F7",
  },
  {
    id: "3",
    name: "Phone",
    icon: "/icons/phone.svg",
    color: "#fff",
    background: "#007dfc",
  },
  {
    id: "4",
    name: "Email",
    icon: "/icons/mail.svg",
    color: "#fff",
    background: "#FF4561",
  },
  {
    id: "5",
    name: "Instagram",
    color: "#fff",
    icon: "/icons/instagram.svg",
    background: "linear-gradient(135deg, #8134AF, #E83B86)",
  },
  {
    id: "6",
    name: "SMS",
    icon: "/icons/sms.svg",
    color: "#000",
    background: "#25d366",
  },
  {
    id: "7",
    name: "Contact Form",
    icon: "/icons/notebook-of-contacts.svg",
    color: "#fff",
    background: "#223B78",
  },
  // {
  //   name: "Poptin",
  //   icon: "/icons/menu-icon-1.png",
  //   color: "#fff",
  //   background: "#49A3B0",
  // },
  {
    id: "8",
    name: "Line",
    icon: "/icons/line.svg",
    color: "#fff",
    background: "#31BC00",
  },
  {
    id: "9",
    name: "Telegram",
    icon: "/icons/telegram.svg",
    color: "#fff",
    background: "#00A9E6",
  },
  {
    id: "10",
    name: "Google Maps",
    icon: "/icons/maps-and-flags.svg",
    color: "#fff",
    background: "#37B067",
  },
  {
    id: "11",
    name: "Viber",
    icon: "/icons/viber.svg",
    color: "#fff",
    background: "#735ff2",
  },
  {
    id: "12",
    name: "Twitter",
    icon: "/icons/twitter.svg",
    color: "#fff",
    background: "#000000",
  },
  {
    id: "13",
    name: "WeChat",
    icon: "/icons/wechat.svg",
    color: "#fff",
    background: "#02D664",
  },
  {
    id: "14",
    name: "SnapChat",
    icon: "/icons/snapchat.svg",
    color: "#fff",
    background: "#F7F400",
  },
  {
    id: "15",
    name: "TikTok",
    icon: "/icons/tik-tok.svg",
    color: "#fff",
    background: "#000000",
  },
  {
    id: "16",
    name: "Skype",
    icon: "/icons/skype.svg",
    color: "#fff",
    background: "#00AAF9",
  },
  {
    id: "17",
    name: "Waze",
    icon: "/icons/waze.svg",
    color: "#fff",
    background: "#6CCCF2",
  },
  {
    id: "18",
    name: "LinkedIn",
    icon: "/icons/linkedin.svg",
    color: "#fff",
    background: "#0074B1",
  },
  {
    id: "19",
    name: "VKontakte",
    icon: "/icons/vkontakte.svg",
    color: "#fff",
    background: "#0077ff",
  },
  {
    id: "20",
    name: "Slack",
    icon: "/icons/slacks.svg",
    color: "#fff",
    background: "#30123B",
  },
  {
    id: "21",
    name: "Discord",
    icon: "/icons/discord.svg",
    color: "#fff",
    background: "#5769F5",
  },
  {
    id: "22",
    name: "Microsoft Teams",
    icon: "/icons/myspace.svg",
    color: "#fff",
    background: "#464eb8",
  },
  // {
  //   id: "24",
  //   name: "Custom5",
  //   icon: "/icons/custom.svg",
  //   color: "#fff",
  //   background: "#464eb8",
  // },
];
export const defaults = {
  whatsapp: {
    channelType: "whatsapp",
    iconUrl: "/icons/whatsapp.svg",
    agents: [],
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "WhatsApp",
    iconBackground: "#54CF61",
    customImage: "",
    enableChatWidget: false,
    chatWidgetText: "Hello! How can we help you?",
    widgetHeading: "Support",
    nickname: "Nickname",
    profileImage: "",
    placeholder: "Type your message...",
    presetMessage: "Hi, I need help with...",
  },
  messenger: {
    channelType: "messenger",
    iconUrl: "/icons/messenger.svg",
    placeholder: "Example: https://m.me/username",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Messenger",
    iconBackground: "#0190F7",
    customImage: "",
  },
  phone: {
    channelType: "phone",
    iconUrl: "/icons/phone.svg",
    placeholder: "Example: +1234567890",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "phone",
    iconBackground: "#007dfc",
    customImage: "",
  },
  email: {
    channelType: "email",
    iconUrl: "/icons/mail.svg",
    placeholder: "Example: john@example.com",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Email",
    iconBackground: "#FF4561",
    customImage: "",
  },
  instagram: {
    channelType: "instagram",
    iconUrl: "/icons/instagram.svg",
    placeholder: "Example: Instagram__username",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Instagram",
    iconBackground: "linear-gradient(135deg, #8134AF, #E83B86)",
    customImage: "",
  },
  sms: {
    channelType: "sms",
    iconUrl: "/icons/sms.svg",
    placeholder: "Example: +1234567890",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "SMS",
    iconBackground: "#25d366",
    customImage: "",
  },
  "contact form": {
    hoverText: "Contact Form",
    channelType: "contact form",
    iconUrl: "/icons/notebook-of-contacts.svg",
    iconBackground: "#223B78",
    fields: [
      {
        id: "1",
        fieldName: "Name",
        value: "",
        fieldPlaceholder: "Enter your name",
        required: true,
        isEnabled: true,
      },
      {
        id: "2",
        fieldName: "Email",
        value: "",
        fieldPlaceholder: "Enter your email",
        required: true,
        isEnabled: true,
      },
      {
        id: "3",
        fieldName: "Phone",
        value: "",
        fieldPlaceholder: "Enter your phone number",
        required: true,
        isEnabled: true,
      },
      {
        id: "4",
        fieldName: "Message",
        value: "",
        fieldPlaceholder: "Enter your message",
        required: true,
        isEnabled: true,
      },
    ],
    contactFormTitle: "Contact Us",
    submitButton: {
      textColor: themColor.white,
      backgroundColor: themColor.primary,
      buttonText: "Send Message",
    },
    toEmail: "Ichonic@gmail.com",
    thankYouMessage: "Thank you for contacting us!",
    redirectVisitors: "",
    closeFormAutomatically: false,
    closeAfterSeconds: 5,
    sendLeadsToEmail: true,
    enableRecaptcha: true,
    showOnDesktop: true,
    showOnMobile: true,
  },
  // poptin: {
  //   channelType: "poptin",
  //   iconUrl: "/icons/menu-icon-1.png",
  //   placeholder: "",
  //   showOnDesktop: true,
  //   showOnMobile: true,
  //   hoverText: "Poptin",
  //   iconBackground: "#49A3B0",
  //   customImage: "",
  // },
  line: {
    channelType: "line",
    iconUrl: "/icons/line.svg",
    placeholder: "Example: http://line.me/ti/p/2a-s5A2B8B",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Chat Line",
    iconBackground: "#31BC00",
    customImage: "",
  },
  telegram: {
    channelType: "telegram",
    iconUrl: "/icons/telegram.svg",
    placeholder: "Example: TelegramTips",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Telegram",
    iconBackground: "#00A9E6",
    customImage: "",
  },
  "google maps": {
    channelType: "google maps",
    iconUrl: "/icons/maps-and-flags.svg",
    placeholder: "Example: https://goo.gl/maps/4m93C84v2DC2",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Google Maps",
    iconBackground: "#37B067",
    customImage: "",
  },
  viber: {
    channelType: "viber",
    iconUrl: "/icons/viber.svg",
    placeholder: "Example: +1234567890",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Viber",
    iconBackground: "#735ff2",
    customImage: "",
  },
  twitter: {
    channelType: "twitter",
    iconUrl: "/icons/twitter.svg",
    placeholder: "Example: Twitter__username",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Twitter",
    iconBackground: "#000000",
    customImage: "",
  },
  wechat: {
    channelType: "weChat",
    iconUrl: "/icons/wechat.svg",
    placeholder: "Example: weChat__ID",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Chat with us on WeChat",
    iconBackground: "#02D664",
    customImage: "",
  },
  snapchat: {
    channelType: "snapchat",
    iconUrl: "/icons/snapchat.svg",
    placeholder: "Example: Snapchat__username.",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Follow us on SnapChat",
    iconBackground: "#F7F400",
    customImage: "",
  },
  tiktok: {
    channelType: "tiktok",
    iconUrl: "/icons/tik-tok.svg",
    placeholder: "Example: @Tiktok__username.",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Follow us on TikTok",
    iconBackground: "#000000",
    customImage: "",
  },
  skype: {
    channelType: "skype",
    iconUrl: "/icons/skype.svg",
    placeholder: "Example: Skype__username",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Chat with us on Skype",
    iconBackground: "#00AAF9",
    customImage: "",
  },
  waze: {
    channelType: "waze",
    iconUrl: "/icons/waze.svg",
    placeholder: "Example: https://waze.com/ul/hdr5ru7vtv",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Find us on Waze",
    iconBackground: "#6CCCF2",
    customImage: "",
  },
  linkedin: {
    channelType: "linkedin",
    iconUrl: "/icons/linkedin.svg",
    placeholder: "Example: LinkedIn__username",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Follow us on LinkedIn",
    iconBackground: "#0074B1",
    customImage: "",
  },
  vkontakte: {
    channelType: "vkontakte",
    iconUrl: "/icons/vkontakte.svg",
    placeholder: "Example: Vk__username",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Follow us on VKontakte",
    iconBackground: "#0077ff",
    customImage: "",
  },
  slack: {
    channelType: "slack",
    iconUrl: "/icons/slacks.svg",
    placeholder: "Example: https://workspace.slack.com",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Chat with us on Slack",
    iconBackground: "#30123B",
    customImage: "",
  },
  discord: {
    channelType: "discord",
    iconUrl: "/icons/discord.svg",
    placeholder: "Example: https://discord.gg/invite__link",
    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Chat with us on Discord",
    iconBackground: "#5769F5",
    customImage: "",
  },
  "microsoft teams": {
    channelType: "microsoft teams",
    iconUrl: "/icons/myspace.svg",
    customImage: "",
    placeholder: "Example: https://teams.microsoft.com/invite__link",

    showOnDesktop: true,
    showOnMobile: true,
    hoverText: "Chat with us on Microsoft Teams",
    iconBackground: "#464eb8",
    customImage: "",
  },
  // custom5: {
  //   iconUrl: "/icons/custom.svg",
  //   placeholder: "Example: custom__username",
  //   iconBackground: "linear-gradient(135deg, #8134AF, #E83B86)",
  //   channelType: "custom5",
  //   showOnDesktop: true,
  //   channelUrl: "user_name",
  //   showOnMobile: true,
  //   hoverText: "custom",
  //   customImage: "",
  // },
  // custom6: {
  //   iconUrl: "/icons/custom.svg",
  //   placeholder: "Example: custom__username",
  //   iconBackground: "linear-gradient(135deg, #8134AF, #E83B86)",
  //   channelType: "custom6",
  //   showOnDesktop: true,
  //   channelUrl: "user_name",
  //   showOnMobile: true,
  //   hoverText: "custom",
  //   customImage: "",
  // },
  // custom7: {
  //   iconUrl: "/icons/custom.svg",
  //   placeholder: "Example: custom__username",
  //   iconBackground: "linear-gradient(135deg, #8134AF, #E83B86)",
  //   channelType: "custom6",
  //   showOnDesktop: true,
  //   channelUrl: "user_name",
  //   showOnMobile: true,
  //   hoverText: "custom",
  //   customImage: "",
  // },
  // custom8: {
  //   iconUrl: "/icons/custom.svg",
  //   placeholder: "Example: custom__username",
  //   iconBackground: "linear-gradient(135deg, #8134AF, #E83B86)",
  //   channelType: "custom6",
  //   showOnDesktop: true,
  //   channelUrl: "user_name",
  //   showOnMobile: true,
  //   hoverText: "custom",
  //   customImage: "",
  // },
  // custom9: {
  //   iconUrl: "/icons/custom.svg",
  //   placeholder: "Example: custom__username",
  //   iconBackground: "linear-gradient(135deg, #8134AF, #E83B86)",
  //   channelType: "custom6",
  //   showOnDesktop: true,
  //   channelUrl: "user_name",
  //   showOnMobile: true,
  //   hoverText: "custom",
  //   customImage: "",
  // },
  // custom10: {
  //   iconUrl: "/icons/custom.svg",
  //   placeholder: "Example: custom__username",
  //   iconBackground: "linear-gradient(135deg, #8134AF, #E83B86)",
  //   channelType: "custom6",
  //   showOnDesktop: true,
  //   channelUrl: "user_name",
  //   showOnMobile: true,
  //   hoverText: "custom",
  //   customImage: "",
  // },
};
export const PERSON = {
  id: "1",
  avatarImage: "https://www.w3schools.com/howto/img_avatar.png",
  avatarColor: "#0fa",
  personTitle: "",
  personDesc: "",
  buttonOnline: "Chat with us",
  buttonOffline: "I will be back soon",
  desktopLink: "",
  mobileLink: "",

  online: false,
  onlineDays: {
    Monday: {
      isOnline: true,
      time: { startTime: "00:00", endTime: "23:59" },
    },
    Tuesday: {
      isOnline: true,
      time: { startTime: "00:00", endTime: "23:59" },
    },
    Wednesday: {
      isOnline: true,
      time: { startTime: "00:00", endTime: "23:59" },
    },
    Thursday: {
      isOnline: true,
      time: { startTime: "00:00", endTime: "23:59" },
    },
    Friday: {
      isOnline: true,
      time: { startTime: "00:00", endTime: "23:59" },
    },
    Saturday: {
      isOnline: true,
      time: { startTime: "00:00", endTime: "23:59" },
    },
    Sunday: {
      isOnline: true,
      time: { startTime: "00:00", endTime: "23:59" },
    },
  },
};
export const PERSON_ARRAY = [PERSON];
export const JSON_PERSON = JSON.stringify(PERSON_ARRAY);
